# Site settings
author: sunny-framework-8369
title: 
header-img: img/home-bg.png
email: mjohnson4685@gmail.com
copyright_name: sunny-framework-8369
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mjj4685

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
